/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * NewQualifierNamePanel.java
 *
 * Created on Jan 19, 2012, 7:33:08 PM
 */
package com.gas.main.ui.molpane.sitepanel.annotation;

import com.gas.common.ui.dialog.DialogUtil;
import com.gas.common.ui.dialog.IVDialog;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;

/**
 *
 * @author dq
 */
public class NewQualifierNamePanel extends javax.swing.JPanel implements IVDialog{

    private String qualifierName;
    
    /** Creates new form NewQualifierNamePanel */
    public NewQualifierNamePanel(String qualifierName) {
        setQualifierName(qualifierName);
        initComponents();
    }

    public String getQualifierName() {
        return qualifierName;
    }

    public void setQualifierName(String qualifierName) {
        this.qualifierName = qualifierName;
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        nameTextField = new javax.swing.JTextField();
        moreBtn = new javax.swing.JButton();

        jLabel1.setText(org.openide.util.NbBundle.getMessage(NewQualifierNamePanel.class, "NewQualifierNamePanel.jLabel1.text")); // NOI18N

        moreBtn.setText(org.openide.util.NbBundle.getMessage(NewQualifierNamePanel.class, "NewQualifierNamePanel.moreBtn.text")); // NOI18N
        moreBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                moreBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(nameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(moreBtn)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(nameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(moreBtn))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

    }// </editor-fold>//GEN-END:initComponents

    private void moreBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_moreBtnActionPerformed
        QualifierListPanel qualifierListPanel = new QualifierListPanel();
        DialogUtil.notify(qualifierListPanel, "All qualifiers", JOptionPane.OK_OPTION);
        String selected = qualifierListPanel.getSelected();
        setQualifierName(selected);
        nameTextField.setText(selected);
    }//GEN-LAST:event_moreBtnActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JButton moreBtn;
    private javax.swing.JTextField nameTextField;
    // End of variables declaration//GEN-END:variables

    @Override
    public boolean validateInput() {
        boolean ret = true;
        if(qualifierName == null || qualifierName.isEmpty()){
            errorMessages.add("Qualifier name cannot be empty.");
            ret = false;
        }
        return ret;
    }

    private List<String> errorMessages = new ArrayList<String>();
    
    @Override
    public List<String> getErrorMessage() {
        return errorMessages;
    }
    
    private int closedButton ;

    @Override
    public int getClosedButton() {
        return closedButton;
    }

    @Override
    public void setClosedButton(int closedButton) {
        this.closedButton = closedButton;
    }
}
